#!/usr/bin/perl
$repopath = shift @ARGV;
$ignore_external_storage = shift @ARGV;

#print "DEBUG: {\"repopath\" : \"$repopath\", \"ignore_external_storage\" : \"$ignore_external_storage\"}\n";

if ( $ignore_external_storage eq "true" ){
  #print "DEBUG: EXITING because ignore_external_storage is true.\n";
  exit 0;
}else{
   #print "DEBUG: EXITING because ignore_external_storage is NOT true.\n";
    while ( ! -e "$repopath/storage/data/config.json" ) {
       sleep 10;
    }
    exit 0;
}
