#!//usr/bin/perl
$tmpl = "/home/azureuser/tflogs/<repo_name>-<month_date>.plan";
$month_date = `date -d "$D" '+%Y';date -d "$D" '+%m';date -d "$D" '+%d'`;
$timezone_difference=6;
$H = `date +'%H'`;chomp $H;
$H = $H-$timezone_difference;
$H = sprintf("%02d",$H);
$M = `date +'%M'`;chomp $M;
$M = sprintf("%02d",$M);
$month_date =~ s/\s+//g;
$month_date = "$month_date-$H$M";
$repo_name = "";
if (scalar(@ARGV)>0){
  $repo_name =  shift @ARGV;
} else {
  die "FATAL ERROR. Plan name must be given on command line after 'mkplan'.";
}
$repo_name =~ s/^\/home\/azureuser\/tflogs\///;
$repo_name =~ s/\-\d{8}\-\d{1,2}\.?\d{1,2}\.plan//;
$repo_name =~ s/\//-/g;

$_ = $tmpl;
s/<repo_name>/$repo_name/;
s/<month_date>/$month_date/;
print "$_\n";

